language: node_js
node_js:
  - "10.9"
cache:
  directories:
    - node_modules
notifications:
  email: true
os:
  - linux
before_install:
  - export NG_CLI_ANALYTICS=ci
  - npm install -g @angular/cli
  - ng analytics off
